volumes:
  n8n_storage:

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=${DB_POSTGRESDB_HOST} # Variable de Render
      - DB_POSTGRESDB_PORT=${DB_POSTGRESDB_PORT} # Variable de Render
      - DB_POSTGRESDB_DATABASE=${DB_POSTGRESDB_DATABASE} # Variable de Render
      - DB_POSTGRESDB_USER=${DB_POSTGRESDB_USER} # Variable de Render
      - DB_POSTGRESDB_PASSWORD=${DB_POSTGRESDB_PASSWORD} # Variable de Render
    ports:
      - 5678:5678
    volumes:
      - n8n_storage:/home/node/.n8n